apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"  # For NLB use "nlb"
spec:
  selector:
    app: springboot-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
