name: CI - Spring Boot

on:
  push:
    branches: [ main, github ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: spring-boot-app
        path: target/*.jar

  docker:
    name: Docker Build with Kaniko
    runs-on: ubuntu-latest
    needs: build
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Download JAR artifact
          uses: actions/download-artifact@v4
          with:
            name: spring-boot-app
            path: target

        - name: Set up Docker config for Kaniko
          run: |
            mkdir -p ./kaniko-config
            echo "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"${{ secrets.DOCKER_USERNAME }}\",\"password\":\"${{ secrets.DOCKER_PASSWORD }}\"}}}" > ./kaniko-config/config.json

        - name: Build and Push Docker image with Kaniko
          uses: addnab/docker-run-action@v3
          with:
            image: gcr.io/kaniko-project/executor:latest
            options: >
                -v ${{ github.workspace }}:/workspace
                -v ${{ github.workspace }}/kaniko-config:/kaniko/.docker
                run: |
                /kaniko/executor \
                    --dockerfile=Dockerfile \
                    --context=dir:///workspace \
                    --destination=docker.io/basivireddy/spring-boot-app:latest \
                    --cleanup